#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
title: Tobias Vente
name: Tobias Vente
description: Ph.D. candiadate @ University of Siegen, DE

layout: single

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include: 
    - _pages

# Site Author
author:
  name             : "Tobias Vente"
  avatar           : "img/profile.jpg"
  bio              : "Lead Decision Scientist @ ShareChat"
  location         : "Edinburgh, UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:tobias.vente@uni-siegen.de"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/tvnte"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tvnte"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tobias-vente-748018178/"

author_profile: true

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/tvnte"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tvnte"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tobias-vente-748018178/"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Analytics
analytics:
  provider               : "google-universal" #, "google-universal", "custom"
  google:
    tracking_id          : "G-TYQS7DQK2Q"
    anonymize_ip         : true #, false (default)
